I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2431, in script
    show caz reassuring onlayer screens at scoot_up
  File "game/script.rpy", line 2431, in <module>
    show caz reassuring onlayer screens at scoot_up
NameError: name 'scoot_awayt' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2431, in script
    show caz reassuring onlayer screens at scoot_up
  File "C:\Users\Difference Engine\Utilities\RenPy 7.3.5\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Difference Engine\Utilities\RenPy 7.3.5\renpy\ast.py", line 1142, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Difference Engine\Utilities\RenPy 7.3.5\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Difference Engine\Utilities\RenPy 7.3.5\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2431, in <module>
    show caz reassuring onlayer screens at scoot_up
NameError: name 'scoot_awayt' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 7.3.5.606
SLASHER, Interrupted 1.0
Thu Oct 15 16:05:01 2020
